module.exports = {
  automock: false,
  browser: false,
  cache: true,
  cacheDirectory: '/tmp/jest_rs',
  clearMocks: true,
  coveragePathIgnorePatterns: [],
  collectCoverageFrom: ['src/**/*.{js,jsx}'],
  dependencyExtractor: null,
  errorOnDeprecated: false,
  filter: null,
  forceCoverageMatch: [],
  forceExit: true,
  globalSetup: null,
  globalTeardown: null,
  globals: {},
  haste: {
    computeSha1: false,
    providesModuleNodeModules: [],
    throwOnModuleCollision: false
  },
  moduleDirectories: ['node_modules'],
  moduleFileExtensions: ['js', 'json', 'jsx', 'ts', 'tsx', 'node'],
  moduleNameMapper: {},
  modulePathIgnorePatterns: [],
  name: 'abc0f54befddf52a6f007e2e956a857c',
  prettierPath: 'prettier',
  resetMocks: false,
  resetModules: false,
  resolver: null,
  restoreMocks: false,
  rootDir: './',
  roots: ['./'],
  runner: 'jest-runner',
  setupFiles: ['./__tests__/setup.js'],
  setupFilesAfterEnv: [],
  skipFilter: false,
  snapshotSerializers: [],
  testEnvironment: 'node',
  testEnvironmentOptions: {},
  testLocationInResults: false,
  testMatch: ['**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)'],
  testPathIgnorePatterns: ['/node_modules/', 'setup.js', 'testHelpers.js'],
  testRegex: [],
  testRunner: './/node_modules/jest-jasmine2/build/index.js',
  testURL: 'http://localhost',
  timers: 'real',
  transform: {
    '^.+\\.[jt]s?$': './/node_modules/babel-jest/build/index.js'
  },
  transformIgnorePatterns: ['/node_modules/'],
  watchPathIgnorePatterns: [],
  verbose: true
}
